[phases.setup]
nixPkgs = ["nodejs_22", "bun"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["bun run build --filter=server"]

[start]
cmd = "bun run apps/server/dist/index.js"

